// Generated by schedule_build.update_site_index. Do not edit by hand.
// Which pages exist for which meeting year; the hub builds its year selector from this.
window.SICB_PAGES = {
  "2027": [
    "schedule",
    "talks",
    "posters",
    "symposia",
    "authors",
    "venue"
  ]
};
window.SICB_PROGRAMMING = false;
